### ISSUE TITLE
current program information

### ISSUE THREAD

**Issue by timoline** [basst85/NextRemoteJs#10]
Beside current channel it also would be nice to have some current program information
maybe we can get this info ?

Something like this you get the current program info

https://web-api-prod-obo.horizon.tv/oesp/v3/NL/nld/web/listings?byEndTime=1582639001962~&byLocationId=65535&byStationId=lgi-nl-prod-master%3A0067&range=1-1&sort=startTime

locationid and stationid, you can get from the channels

and the endtime you can get at this url
https://web-api-prod-obo.horizon.tv/oesp/v3/NL/nld/web/time/65535

**Comment by basst85** [comment]
> Beside current channel it also would be nice to have some current program information
> maybe we can get this info ?
> 
> Something like this you get the current program info
> 
> https://web-api-prod-obo.horizon.tv/oesp/v3/NL/nld/web/listings?byEndTime=1582639001962~&byLocationId=65535&byStationId=lgi-nl-prod-master%3A0067&range=1-1&sort=startTime
> 
> locationid and stationid, you can get from the channels
> 
> and the endtime you can get at this url
> https://web-api-prod-obo.horizon.tv/oesp/v3/NL/nld/web/time/65535

Hi Timo!

Thanks for sharing this info. Much appreciated !
Feel free to create an Pull Request with support for this 👍

**Comment by timoline** [comment]
I got it almost working but with a different url:
`https://web-api-prod-obo.horizon.tv/oesp/v3/NL/nld/web/listings/crid%3A~~2F~~2Fbds.tv~~2F104306153%2Cimi%3A814e369e5fb2ccae4db9e755f63d79989ad2c636?byLocationId=65535`

Only crid and locationid is needed ;-)
