### ISSUE TITLE
Connection Errors

### ISSUE THREAD

**Issue by Anjerlaan** [basst85/NextRemoteJs#14]
Hi,

I have a question about NextRemote.js....not sure if you can help me but you never know
I have installed this on a Raspberry Pi (Raspbian Buster).

On the same Pi I also run Node-Red, which I use to talk with to the NextRemote.js.  with http requests (see 1st picture).
It is a very simple flow...I only want to turn the Next ON or OFF (part of a domoticz group which turns on/off all my AV devices in a certain order)

in the example picture below is the flow to turn the Next on/off
and one flow which syncs the Next on/off button with a Domoticz on/off switch, when the Next remote is used

![image](https://user-images.githubusercontent.com/18295963/115141128-01e17700-a03b-11eb-9fd9-b3920effc995.png)

The sync flow is catching the Status() value of your script, the blue node injector is a heartbeat of 1 second to retrieve the lastest state of the Next.
But every day (at a random time) I get connection errors shown in the picture below. If I reset the Pi, the connection is working again untill the next next ;-) connection error

![image](https://user-images.githubusercontent.com/18295963/115141176-38b78d00-a03b-11eb-8f83-bfe4bc38d09e.png)

Do you have any idea what may cause the connection error?

**Comment by basst85** [comment]
@Anjerlaan Hi!

This looks like an issue with the session. I think this expires after a day. And in the code, there isn't a function to renew the session.

**Comment by timoline** [comment]
The constants.js isn't used (yet)
