### ISSUE TITLE
Support for multiple boxes

### ISSUE THREAD

**Issue by Sholofly** [basst85/NextRemoteJs#3]
Is it possible to support multiple boxes? It looks like it's taking the last one now...
Btw, do you know where to find more information about the mqtt topics of this STBs?

**Comment by basst85** [comment]
Hello! 
Yes, i think that's possible with some small changes to the code. You have to manage multiple setopbox id's instead of just one. But unfortunately i can't test this, because i only have 1 Ziggo Next box,

I have found the used MQTT commands by reverse engineering ziggogo.tv, don;t know where to find more :-(

**Comment by Sholofly** [comment]
Thanks for your reply. i managed to fix it for my home automation client.
also I found the endpoint to retrieve the current playing program.

Op zo 25 aug. 2019 21:39 schreef basst85 <notifications@github.com>:

**Comment by nelbs** [comment]
> Hello!
> Yes, i think that's possible with some small changes to the code. You have to manage multiple setopbox id's instead of just one. But unfortunately i can't test this, because i only have 1 Ziggo Next box,
> 
> I have found the used MQTT commands by reverse engineering ziggogo.tv, don;t know where to find more :-(

Hello,
How did you achieved this? 

I would like to find the command to get the current channel when the remote is used. I inspected ziggogo.tv and found a long json code with a lot of functions related to the use of the mediabox. see the snippet below. 

My programming skills are to limited to understand the code but is this the place where we can find the mqtt commands??

```
            key: "pushToTv",
            value: function(e, t) {
                var n = e.boxId
                  , r = e.sourceType
                  , o = e.source
                  , i = e.relativePosition;
                Object(C.f)(r, "sourceType"),
                Object(C.d)(i, "relativePosition");
                var a = this._client
                  , u = a.comsGroupId;
                (0,
                a.publish)(u + "/" + n, {
                    id: Object(I.a)(),
                    type: N.n,
                    source: this.source,
                    status: {
                        sourceType: r,
                        source: o,
                        relativePosition: i
                    }
                }, {
                    retain: 0,
                    qos: N.B.AT_MOST_ONCE
                }, t)
            }
        }, {
            key: "pullFromTv",
            value: function(e, t) {
                this.publishCommand(N.m, e, {}, void 0, t)
            }
        }, {
            key: "keyEvent",
            value: function(e) {
                var t = arguments.length > 1 && void 0 !== arguments[1] ? arguments[1] : {}
                  , n = t.uniCodeChar
                  , r = t.w3cKey;
                n && Object(C.d)(n, "uniCodeChar"),
                r && Object(C.f)(r, "w3cKey"),
                Object(C.a)(n || r, 'Either "uniCodeChar" or "w3cKey" should be provided'),
                this.publishCommand(N.f, e, {
                    uniCodeChar: n,
                    w3cKey: r,
                    eventType: "keyDownUp"
                }, {
                    retain: 0,
                    qos: N.B.AT_MOST_ONCE
                })
            }
```

**Comment by basst85** [comment]
> > Hello!
> > Yes, i think that's possible with some small changes to the code. You have to manage multiple setopbox id's instead of just one. But unfortunately i can't test this, because i only have 1 Ziggo Next box,
> > I have found the used MQTT commands by reverse engineering ziggogo.tv, don;t know where to find more :-(
> 
> Hello,
> How did you achieved this?
> 
> I would like to find the command to get the current channel when the remote is used. I inspected ziggogo.tv and found a long json code with a lot of functions related to the use of the mediabox. see the snippet below.
> 
> My programming skills are to limited to understand the code but is this the place where we can find the mqtt commands??
> 
> ```
>             key: "pushToTv",
>             value: function(e, t) {
>                 var n = e.boxId
>                   , r = e.sourceType
>                   , o = e.source
>                   , i = e.relativePosition;
>                 Object(C.f)(r, "sourceType"),
>                 Object(C.d)(i, "relativePosition");
>                 var a = this._client
>                   , u = a.comsGroupId;
>                 (0,
>                 a.publish)(u + "/" + n, {
>                     id: Object(I.a)(),
>                     type: N.n,
>                     source: this.source,
>                     status: {
>                         sourceType: r,
>                         source: o,
>                         relativePosition: i
>                     }
>                 }, {
>                     retain: 0,
>                     qos: N.B.AT_MOST_ONCE
>                 }, t)
>             }
>         }, {
>             key: "pullFromTv",
>             value: function(e, t) {
>                 this.publishCommand(N.m, e, {}, void 0, t)
>             }
>         }, {
>             key: "keyEvent",
>             value: function(e) {
>                 var t = arguments.length > 1 && void 0 !== arguments[1] ? arguments[1] : {}
>                   , n = t.uniCodeChar
>                   , r = t.w3cKey;
>                 n && Object(C.d)(n, "uniCodeChar"),
>                 r && Object(C.f)(r, "w3cKey"),
>                 Object(C.a)(n || r, 'Either "uniCodeChar" or "w3cKey" should be provided'),
>                 this.publishCommand(N.f, e, {
>                     uniCodeChar: n,
>                     w3cKey: r,
>                     eventType: "keyDownUp"
>                 }, {
>                     retain: 0,
>                     qos: N.B.AT_MOST_ONCE
>                 })
>             }
> ```

Hi! Check the latest commit from today :-)
