### ISSUE TITLE
Directly use powerkey

### ISSUE THREAD

**Issue by rgerrie** [basst85/NextRemoteJs#4]
How can I execute the powerKey command directly?
is this possible with a json post? or is there another way?

Thanks!

**Comment by basst85** [comment]
Hello!

What do you exactly mean with "directly"?
You first have to a authenticate and get the correct device (Next box).

**Comment by rgerrie** [comment]
by direct I mean without using the web interface. Everything works, but I want to switch off the media box with forexample an http request

**Comment by basst85** [comment]
You can perform a POST request to http://localhost:8080/api with the following JSON body:
`{action: 'powerKey'}`

localhost can also be a domain if you host it on a server, but that's not very secure because there is no authentication on /api

**Comment by rgerrie** [comment]
Thanks!!
