### ISSUE TITLE
possible to switch off the TV

### ISSUE THREAD

**Issue by rgerrie** [basst85/NextRemoteJs#5]
If I switch off the mediabox with the remote control, the TV is also switched off by the mediabox. When i use the power key in NextRemoteJs, it will switch off the media box only. The TV stays on. Is it also possible to switch off the mediabox and the TV with NextRemoteJs?

Thanks

**Comment by basst85** [comment]
Unfortunately I didn't found a method for that.
Is this possible via https://ziggogo.tv or via the app?

**Comment by rgerrie** [comment]
you're right. If I use the off button with the app, the TV also stays on.
Thank you for trying!
