### ISSUE TITLE
CPE.getUiStatus only works when ziggogo.tv app is running 

### ISSUE THREAD

**Issue by Sholofly** [basst85/NextRemoteJs#7]
Hi Bas, I need your help. I'm trying to make your component work for python. In your code you have a mqtt post to CPE.getUIStatus But that only sends messages when connected to the ziggogo.tv web app.
My best guess is that something else in de code of ziggogo.tv is done to make this possible. Are you willing to help me reverse engineer the code to find out why ziggogo.tv is working, but your code doesn't? Since my javascript skills are not that good, maybe you can find your way in it? If you are not can you tell me how you reverse engineered te code, so i can try it myself?

**Comment by basst85** [comment]
Hi! Check the latest [commit](https://github.com/basst85/NextRemoteJs/commit/abba6dd9181a945988cde66dff8271d680c41dac)  from today :-)

**Comment by Sholofly** [comment]
Wow, I'm gonna test that tomorrow. Looks good! Is it smart thinking or did
you reverse engineer it and found the way it's done on the website?

Op zo 19 jan. 2020 22:37 schreef basst85 <notifications@github.com>:

**Comment by basst85** [comment]
> Wow, I'm gonna test that tomorrow. Looks good! Is it smart thinking or did you reverse engineer it and found the way it's done on the website?

A little bit of reverse-engineering on ziggogo.tv, via developer-tools (F12) in Chrome -> Network -> WS. And you can also set the local storage value of "__DEBUG_logLevel" to 1, then you see all MQTT messages in console. 👍
